[package]
name = "push"
version = "0.1.0"
edition = "2024"

[dependencies]
midir = "0.10.3"
thiserror = "2.0.17"
push2_display = { git = "https://github.com/mbracher/push2_display.git" }
embedded-graphics = "0.8.1"
ron = "0.11.0"
serde = { version = "1.0.228", features = ["derive"] }
